# Page settings
#baseurl = "localhost:1313"
baseurl = "deimosfr.github.io/peace-in-dordogne.com/"
title = "Peace in Dordogne"
languageCode = "fr-fr"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Peace in Dordogne"
    home = "Accueil"
    work = "Activitées"
    testimonials = "Témoignages"
    services = "Gîte"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "English version"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Vacances relaxantes en Dordogne"
    subtitle = "Venez découvrir cette magnifique région dans ce Gîte confortable à proximité de nombreuses activités et sites historiques"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Gîte"
    description = "Charmant Gîte de 4 pièces : 3 chambres, séjour tout équipé avec cuisine, 2 salles d'eau, piscine, barbecue et grand jardin."
    url = "#video"
    button = "Je veux en savoir +"
    icon = "icon-home"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Piscine"
    description = "Grande piscine clôturée de 12m x 5m et sécurisée, profondeur de 90 cm à 2m. Température allant de 18° jusqu'à 30° l'été."
    url = "#video"
    button = "Je veux plonger"
    icon = "icon-support"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Massage"
    description = "Relaxez-vous ou soulagez vos douleurs grâce à Rosemary diplômée en Shiatsu et Réflexologie. Les bienfaits sont immédiats."
    url = "#tarifs"
    button = "Je veux un massage"
    icon = "icon-heart"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "<div id='video'></div><br />Découvrez la Dordogne en video"
    icon = "icon-play2"
    url = "https://youtu.be/BdSWuP2bkbs"


  # Work section
  [params.work]
    enable = true
    title = "Activitées"
    description = "Découvrez un havre de paix au coeur de la Dordogne. Le Gîte est situé à 2 km du centre de Domme classé dans les plus beaux villages de France. Plongez dans une région remplie d’histoire, en visitant Sarlat-la-Caneda, ville historique du XIIème siècle, ainsi que les fameuses grottes de Lascaux. Détendez-vous dans un cadre zen grâce à la piscine, aux massages, le barbecue et le grand jardin."
    footertext = "Mais également la visite des grottes, des châteaux, musées, gastronomie, vélos, cours de pilotage à l'aérodrome de Domme..."

    [[params.work.row]]
      img = "activ_massages.jpg"
      alt = "Massages"
      title = "Massages shiatsu et réflexologie"
      subtitle = "Vôtre hôte est aux petits soins pour vous"

    [[params.work.row]]
      img = "activ_canoe.jpg"
      alt = "Canoës"
      title = "Canoës"
      subtitle = "Faites du Canoë sur la Dordogne à 5 min"

    [[params.work.row]]
      img = "activ_equitation.jpg"
      alt = "Equitation"
      title = "Equitation"
      subtitle = "Trottez dans la nature au milieu de la fôret"

    [[params.work.row]]
      img = "activ_mongolfiere.jpg"
      alt = "Mongolfière"
      title = "Mongolfière"
      subtitle = "Admirez la Dordogne vue du ciel"

    [[params.work.row]]
      img = "activ_randonnees.jpg"
      alt = "Randonnées"
      title = "Randonnées"
      subtitle = "Profitez de la nature et des villages historiques"

    [[params.work.row]]
      img = "activ_golf.jpg"
      alt = "Golf"
      title = "Golf"
      subtitle = "Faites votre plus beau swing à 10 min"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Témoignages"
    description = "Après leur séjour, voici ce qu'ils en ont pensé"

    [[params.testimonials.item]]
      quote = "&ldquo;L'habitation de Rosemary est très bien située tout près de la commune de Domme, on peut y aller à pied en moins de 1/2 heures. Nous avons apprécié sa piscine qui est très bien entretenu, nous avons profité de la terrasse à tous les repas. Je conseille les massages de Rosemary, un plus ! Rosemary à tout fait pour que nous passions un très bon séjour, merci&rdquo;"
      person = 'Séverine'
      img = "feedback_severine.jpg"
      alt = "Séverine"

    [[params.testimonials.item]]
      quote = "&ldquo;La maison de Rosemary est un havre de paix. Tout est calme, les chambres confortables, deux salles de douche indispensables quand on est 6. Nous venions avec un bébé de 14 mois et Rosemary a tout fait pour que nous puissions voyager léger en nous mettant à disposition une chaise haute et un lit parapluie. La piscine est hyper bien entretenue et ne sens pas le chlore. Rosemary très discrète est toujours là si nous avons besoin de quelque chose. Nous avons quitté à regret cette maison et sa propriétaire qui aura été une belle rencontre. La maison est à 5 mn de Domme en voiture, 20 mn de Sarlat et entre 30 et 45 minutes de nombreux sites touristiques du Périgord Noire.&rdquo;"
      person = 'Isabelle'
      img = "feedback_isabelle.jpg"
      alt = "Isabelle"

    [[params.testimonials.item]]
      quote = "&ldquo;Nous avons été très bien accueillis par Rosemary, dans sa maison très agréable, au calme, en pleine campagne tout près de Domme. Le logement est bien équipé, très pratique, la piscine super. La maison est idéalement située pour des excursions vers le principaux sites touristiques de la région. Un petit bonus: séance de réflexologie très bénéfique. Une semaine de vacances en famille très réussie, malgré un ou deux jours de pluie. Merci à Rosemary !&rdquo;"
      person = 'Antoine'
      img = "feedback_antoine.jpg"
      alt = "Person3"

  # Le Gîte en détails
  [params.services]
    enable = true
    title = "Le Gîte en détails"
    description = "Le Gîte se trouve dans endroit très calme, boisé, sur une colline. <br /> 6 personnes peuvent être accueillies. Vous disposez de 3 chambres : 2 chambres avec lits doubles et 1 chambre simple, avec 2 lits simples. 1 séjour avec cuisine toute équipée : cuisinière, four, lave-vaisselle, réfrigérateur, machine à laver. 2 salles d'eau, et un WC séparé. <br /> Une connexion WIFI et la TV en anglais et en français pourront vous divertir. <br /> Vous pourrez déguster de bonnes grillades sur le barbecue. Profitez du grand jardin, avec balançoires. <br /> Les animaux sont acceptés, cependant le terrain n'est pas clôturé."

    [[params.services.item]]
      title = "Grande Piscine"
      description = "La piscine est privative, vous pourrez donc vous vous baignez et bronzer en toute tranquilité"
      icon = "icon-support"

    [[params.services.item]]
      title = "Barbecue"
      description = "Le Barbecue est également privatif. Vous pourrez déguster vos grillades sur la terrasse"
      icon = "icon-fire"
    [[params.services.item]]
      title = "Grand terrain de 1000 m2"
      description = "Grand jardin fleuri avec balançoire. Idéal pour se ressourcer et se trouver au plus près de la nature"
      icon = "icon-picture"

      [[params.services.item]]
      title = "Gîte très bien situé"
      description = "Vous serez très bien situés pour visiter les nombreux Châteaux et faire toutes les activitées de la région"
      icon = "icon-directions"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  [params.pricing]
    enable = true
    title = "Tarifs"
    description = "Voici les tarifs par mois et par activités"

    [[params.pricing.item]]
      column1 = "Mois"
      column2 = "Prix à la semaine"
      content = [
        ["Avril", "525 €"],
        ["Mai", "600 €"],
        ["Juin", "600 €"],
        ["Juillet", "700 €"],
        ["Août", "800 €"],
        ["Septembre", "600 €"],
        ["Octobre", "500 €"],
      ]
      S'ajoute 50 euros de frais de ménage

    [[params.pricing.item]]
      column1 = "Massages"
      column2 = "Prix"
      content = [
        ["Shiatsu et réflexologie (30 min)", "35 €"],
        ["Shiatsu et réflexologie (1h)", "50 €"],
      ]

  [params.calendar]
    enable = true
    title = "Calendrier des disponibilités"
    description = "Vous trouverez ici les informations sur les réservations déjà en cours"
    url = "https://calendar.google.com/calendar/embed?src=rosemary.warder%40gmail.com&ctz=Europe%2FParis&showTitle=0"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact et réservation"
    description = "Vous pouvez me contacter pour toute question ou réservation"

    # Google Form for information
    GFormEnable = true
    GFormUrl = "https://docs.google.com/forms/d/e/1FAIpQLSdl5vUq92age3ErZBeQUGOLOpVvrfTKf5GcI-ZLJyxz8VAW-g/viewform?embedded=true"
    GFormWidth = "480"
    GFormHeight = "983"

    # Reservation button
    buttonName = "Réservation en ligne"
    buttonUrl = "https://goo.gl/forms/p3j6jwIOGsSOkZpI3"

    # Google Maps
    map = true
    mapUrl = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13759.50720509555!2d1.219113269715227!3d44.790213950463794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDTCsDQ3JzI0LjgiTiAxwrAxMyc0MC4zIkU!5e1!3m2!1sfr!2sfr!4v1549920527165"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Route de la Vergnolle, 24250 Domme"],
        ["icon-location-pin", "<a href='https://goo.gl/maps/Po8P2wnUbL22' target='_blank'>44°47'24.8\"N 1°13'40.3\"E<br />44.790213, 1.227868</a>"],
      ]

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Partagez ce site sur les réseaux sociaux'
    links = [
      ["icon-facebook", "https://www.facebook.com/sharer/sharer.php?u=www.peace-in-dorgogne.com"],
      ["icon-twitter", "https://twitter.com/intent/tweet?text=Vivez%20un%20incroyable%20séjour%20au%20Gite%20de%20Rosemary%20http://www.peace-in-dorgogne.com"],
    ]
